### ISSUE TITLE
A typo in README.md

### ISSUE THREAD

**Issue by meandmytram** [mhauru/ncon#1]
In this line:

Here the last index of a and the first index of b are contracted. The result is a tensor with two free indices, labeled by -1 and -2. The one labeled with -1 becomes the first index of the result. If we gave the additional argument forder=[-2,-1] the tranpose would be returned instead.

The last sentence should read:

If we gave the additional argument forder=[-2,-1] the transpose would be returned instead.

(I have fixed the word "transpose")

**Comment by mhauru** [comment]
Fixed now, thanks for pointing this out!
