### ISSUE TITLE
Adding TYPE HINTING

### ISSUE THREAD

**Issue by indiano68** [mhauru/ncon#3]
I would like to add type hinting to the source in order to work better with the linter in my own code that depends on ncon.
Would you be accepting a pull request that edits some of the logic to allow type hinting?

Reason for my question is the following:
```python
if not isinstance(v[0], Iterable):
   # v is not a list of lists, so make it such.
    v = [v]
```
Those are lines 38 to 40 in the source, such assignments make it very difficult to define a type for v.

**Comment by mhauru** [comment]
Sure, if the interface remains the same then happy to accept such a PR. The above could just be something like
```
w = v if isinstance(v[0], Iterable) else [v]
```

**Comment by indiano68** [comment]
nice! I will probably not do much more than create some buffer variables to fix conflicts. Happy to support, thanks for the nice library.
